Pr
Ontology2024/mobile pull request #40
Opened 2024-11-20 16:08 UTC by wnddkdpcqkd

2024-11-21 01:40 UTC, JerryG0228 reviewed
.

2024-11-21 01:40 UTC, JerryG0228 reviewed
asd

2024-11-21 01:45 UTC, JerryG0228 requested changes, later dismissed
ㅁㄴㅇ

2024-11-21 01:52 UTC, merged

2024-11-23 07:09 UTC, ENvironmentSet commented
도대체 얼마나 작업하신 거예요 ㅋㅋㅋㅋㅋ